---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - wget
  - go
  - ag 
  - terraform
  - terraform-inventory
  - lastpass-cli
  - mysql
  - vault
  - dcos-cli
  - jq
  - openssl


# homebrew cask applications
cask_applications:
  - docker
  - alfred
  - spotify
  - steam
  - visual-studio-code
  - qq
  - skype
  - evernote
  - championify
  - spectacle

downloads:
  keepass:
    name: KeePassX
    url: https://www.keepassx.org/releases/0.4.4/KeePassX-0.4.4.dmg
    dest: "{{general.local_home}}/Downloads/KeePassX-0.4.4.dmg"
  git-bash-completion:
    name: GitBashCompletion
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: "{{general.local_home}}/.git-completion.bash"
  solarized:
    name: Solarized
    url: http://ethanschoonover.com/solarized/files/solarized.zip
    dest: "{{general.local_home}}/Downloads/solarized.zip"
   # zwift:
   #   name: Zwift
   #   url: http://cdn.zwift.com/app/ZwiftOSX.dmg
   #   dest: "{{general.local_home}}/Downloads/ZwiftOSX.dmg"
   # suuntolink:
   #   name: Suunto Movescount link
   #   url: http://suuntolink.static.movescount.com/Suuntolink_installer.dmg
   #   dest: "{{general.local_home}}/Downloads/Suuntolink_installer.dmg"

